### ISSUE TITLE
Back button shows up on action bar after registration/logging in

### ISSUE THREAD

**Issue by rclai** [NativeScript/sample-Friends#14]
How do you guys hide it?

**Comment by jlooper** [comment]
You can take a look at the sample-Groceries code for methods of hiding that back button. There's a util file handling the action bar that's very nice (master branch)

**Comment by rclai** [comment]
Thanks.

https://github.com/NativeScript/sample-Groceries/blob/a1857ea5dcd364f7e4e7dcb5ea7916435f106844/app/shared/utils/action-bar-util.js
